Updates to config files

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -231,6 +231,42 @@ function genpass() {
 	fi
 }
 
+function proxy_on() {
+    export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com,sharenet"
+
+    if (( $# > 0 )); then
+        valid=$(echo $@ | sed -n 's/\([0-9]\{1,3\}.\)\{4\}:\([0-9]\+\)/&/p')
+        if [[ $valid != $@ ]]; then
+            >&2 echo "Invalid address"
+            return 1
+        fi
+
+        export http_proxy="http://$1/"
+        export https_proxy=$http_proxy
+        export ftp_proxy=$http_proxy
+        export rsync_proxy=$http_proxy
+        echo "Proxy environment variable set."
+        return 0
+    fi
+
+    export https_proxy=$http_proxy
+    export ftp_proxy=$http_proxy
+    export rsync_proxy=$http_proxy
+    export HTTP_PROXY=$http_proxy
+    export HTTPS_PROXY=$http_proxy
+    export FTP_PROXY=$http_proxy
+    export RSYNC_PROXY=$http_proxy
+	echo -e "Proxy turned on";
+}
+
+function proxy_off(){
+    unset http_proxy
+    unset https_proxy
+    unset ftp_proxy
+    unset rsync_proxy
+	echo -e "Proxy turned off";
+}
+
 ##
 ## Simple password management in ksh-compatible shell
 ## You'll need a unix-like system and a working GPG configuration
@@ -351,12 +387,13 @@ alias p2='sudo ln -sf /usr/bin/python2 /usr/bin/python'
 alias p3='sudo ln -sf /usr/bin/python3 /usr/bin/python'
 alias updatetime='sudo ntpclient -s -h pool.ntp.org'
 alias x='dtrx'
+alias sd='svn diff -x "-p -u -w"'
 
 
 # Variables ---------------------------------------------------------------
 export PROMPT_COMMAND=prompt
 export PS2="--> "
-export PATH=/usr/local/sbin:/usr/local/bin:~/scripts:$PATH
+export PATH=/usr/local/sbin:/usr/local/bin:~/scripts:~/bin:$PATH
 export GPGKEY=FFFFFFFF
 export LC_CTYPE=en_US.UTF-8
 export LC_ALL=en_US.UTF-8
